version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
    site_django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: site_local_django
    container_name: site_django
    depends_on:
      - site_postgres
    volumes:
      - .:/site
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8008:8008"
    command: /start

    site_postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: site_production_postgres
    container_name: site_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5430:5430"