version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  site_django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: site_local_django1
    container_name: site_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/site
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8008:8008"
    links:
      - redis
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: site_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"
  redis:
    restart: always
    image: "redis:alpine"
    ports:
      - "6379:6379"