# Generated by Django 3.0.3 on 2020-07-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_auto_20200723_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted for processing', 'Accepted for processing'), ('Performed', 'Performed'), ('Paid', 'Paid')], max_length=200),
        ),
    ]
