# Generated by Django 3.0.3 on 2020-02-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_auto_20200224_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Accepted for processing', 'Accepted for processing'), ('Performed', 'Performed')], max_length=200),
        ),
    ]
