# Generated by Django 3.0.3 on 2020-02-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_auto_20200212_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted for processing', 'Accepted for processing'), ('Paid', 'Paid'), ('Performed', 'Performed')], max_length=200),
        ),
    ]
