# Generated by Django 3.0.3 on 2020-02-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_auto_20200224_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={},
        ),
        migrations.AlterField(
            model_name='member',
            name='member',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='member',
            field=models.CharField(default='', max_length=20),
        ),
    ]
