# Generated by Django 3.0.3 on 2020-07-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_auto_20200725_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Performed', 'Performed'), ('Accepted for processing', 'Accepted for processing')], max_length=200),
        ),
    ]
