# Generated by Django 3.0.3 on 2020-02-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_auto_20200212_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Performed', 'Performed'), ('Paid', 'Paid'), ('Accepted for processing', 'Accepted for processing')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
