# Generated by Django 2.2.3 on 2019-10-03 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_auto_20190930_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='ecomapp.Cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('Pickup', 'Pickup'), ('Delivery', 'Delivery')], default='Pickup', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Performed', 'Performed'), ('Paid', 'Paid'), ('Accepted for processing', 'Accepted for processing')], max_length=200),
        ),
    ]
