# Generated by Django 3.0.3 on 2020-07-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_auto_20200727_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Accepted for processing', 'Accepted for processing'), ('Performed', 'Performed')], max_length=200),
        ),
    ]
