# Generated by Django 3.0.3 on 2020-02-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_auto_20200224_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted for processing', 'Accepted for processing'), ('Paid', 'Paid'), ('Performed', 'Performed')], max_length=200),
        ),
    ]
