# Generated by Django 2.2.3 on 2019-10-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_auto_20191003_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted for processing', 'Accepted for processing'), ('Performed', 'Performed'), ('Paid', 'Paid')], max_length=200),
        ),
    ]
