# Generated by Django 3.0.3 on 2020-02-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_product_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Performed', 'Performed'), ('Accepted for processing', 'Accepted for processing')], max_length=200),
        ),
    ]
