# Generated by Django 3.0.3 on 2020-02-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_auto_20200218_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('author', models.CharField(max_length=120)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='comments',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Performed', 'Performed'), ('Accepted for processing', 'Accepted for processing'), ('Paid', 'Paid')], max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.ManyToManyField(blank=True, to='ecomapp.Comment'),
        ),
    ]
