# Generated by Django 3.0.3 on 2020-09-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0010_auto_20200919_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_session',
            field=models.CharField(max_length=50),
        ),
    ]
