# Generated by Django 2.2.3 on 2019-10-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0010_auto_20191007_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_code',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='expiry_date',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Performed', 'Performed'), ('Accepted for processing', 'Accepted for processing'), ('Paid', 'Paid')], max_length=200),
        ),
    ]
