# Generated by Django 2.2.3 on 2019-10-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0017_auto_20191016_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Accepted for processing', 'Accepted for processing'), ('Paid', 'Paid'), ('Performed', 'Performed')], max_length=200),
        ),
    ]
