# Generated by Django 2.2.3 on 2019-10-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0019_auto_20191016_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Performed', 'Performed'), ('Accepted for processing', 'Accepted for processing'), ('Paid', 'Paid')], max_length=200),
        ),
    ]
