FROM nginx:1.19.0-alpine
# RUN rm /etc/nginx/conf.d/default.conf
# COPY ./nginx/conf.d/default.conf /etc/nginx/conf.d
# COPY ./static /static
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d